# Importing the PCA module

In [1]:
from PCA import *

# Creating and Normalizing the Data

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
Xbar = normalize(A)
print(Xbar)

[[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]


# Creating a PCA Instance

In [3]:
pca = PCA(num_components = 2)
#fit data to PCA
pca.fit(Xbar)

In [4]:
#print PCA components
print(pca.components_)
print(pca.explained_variance_)

[[ 5.77350269e-01  5.77350269e-01  5.77350269e-01]
 [-3.58032269e-17 -7.07106781e-01  7.07106781e-01]]
[ 4.00000000e+00 -2.46519033e-32]


In [5]:
transformed = pca.transform(Xbar)
print(transformed)

[[-2.32379001  0.        ]
 [-0.77459667  0.        ]
 [ 0.77459667  0.        ]
 [ 2.32379001  0.        ]]


# Sklearn PCA

In [6]:
from sklearn.decomposition import PCA as SKPCA

In [7]:
skpca = SKPCA(n_components=2)
X = skpca.fit(Xbar)

In [8]:
print(skpca.components_)
print(skpca.explained_variance_)

[[ 0.57735027  0.57735027  0.57735027]
 [-0.81649658  0.40824829  0.40824829]]
[4.00000000e+00 4.93038066e-32]


In [9]:
sk_transformed = skpca.transform(Xbar)
print(sk_transformed)

[[-2.32379001e+00 -6.41718328e-16]
 [-7.74596669e-01 -1.69344564e-16]
 [ 7.74596669e-01  1.69344564e-16]
 [ 2.32379001e+00  6.41718328e-16]]


# Benchmarking

In [10]:
np.testing.assert_almost_equal(transformed, sk_transformed)
print(np.square(transformed - sk_transformed).sum())

1.3739980535162503e-30
